/* Generated by scripts/gen-props.mjs from dist/*.d.ts - run `pnpm docs:props`, do not edit by hand.
   The prop JSDoc on each public props interface is the single source of truth. */
import type { PropRow } from '../components/PropsTable';

export interface NestedType {
  name: string;
  rows: PropRow[];
}

export const GENERATED_PROPS: Record<string, PropRow[]> = {
  button: [
    {
      name: 'htmlProps',
      type: 'ButtonRestProps',
      description:
        'Standard <button> attributes (onClick, name, form, aria-*, data-*, ...) forwarded verbatim. Bare `<button>` attributes also pass through directly; `htmlProps` wins on conflict.',
    },
    {
      name: 'variant',
      type: "'primary' | 'secondary' | 'ghost' | 'danger' | 'link' | 'unstyled'",
      default: "'primary'",
      description:
        "Visual weight / intent. `unstyled` emits base chrome only (sizing, focus ring, layout) with no skin - for local re-skins via `className`, e.g. Alert's tone action.",
    },
    {
      name: 'ref',
      type: 'Ref<HTMLButtonElement>',
      description: 'Forwarded to the underlying <button> (React 19 ref-as-prop).',
    },
    {
      name: 'size',
      type: "'sm' | 'md' | 'lg' | 'icon'",
      default: "'md'",
      description: 'Control height. sm 28px - md 36px (default) - lg 40px.',
    },
    {
      name: 'type',
      type: "'button' | 'submit' | 'reset'",
      default: "'button'",
      description: '`submit` / `reset` / `button`.',
    },
    { name: 'disabled', type: 'boolean', description: 'Disable the control (also implied by `loading`).' },
    {
      name: 'loading',
      type: 'boolean',
      description: 'Loading - swaps content for a spinner and makes the button inert.',
    },
    { name: 'fullWidth', type: 'boolean', description: 'Stretch to fill the container width.' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the button.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the button.' },
    { name: 'children', type: 'ReactNode', description: 'Button label.' },
    { name: 'onClick', type: 'React.MouseEventHandler<HTMLButtonElement>', description: 'Click handler' },
    { name: 'onPointerDown', type: 'React.PointerEventHandler<HTMLButtonElement>', description: 'Pointer handler' },
  ],
  collapse: [
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLDivElement>, keyof CollapseOwnProps> & DataAttributes',
      description: 'Standard <div> attributes (aria-*, data-*, ...) forwarded to the root.',
    },
    {
      name: 'open',
      type: 'boolean',
      description:
        'Open/closed state. Closed content is also removed from the tab order, the accessibility tree and hit-testing once the exit transition completes; reopening restores it before the entrance runs.',
    },
    { name: 'axis', type: "'height' | 'width'", default: "'height'", description: 'Axis to animate.' },
    {
      name: 'fade',
      type: 'boolean',
      description: 'Also cross-fade contents while resizing; follows `duration` / `ease`.',
    },
    {
      name: 'innerClassName',
      type: 'string',
      description:
        'Class applied to the inner measured wrapper - the clipping element (overflow: hidden). Content whose focus ring sits flush to its edge needs padding there, or the ring clips.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      default: "duration 'slow' + ease 'entrance' (fade-out: 'base' + 'standard')",
      description:
        "Size (and fade) transition timing - motion tokens only, each field one token or `{ open, close }`, e.g. `{ duration: { close: 'fast' }, ease: { close: 'exit' } }`. `null` disables the transition (open/close snap instantly).",
    },
    { name: 'as', type: 'keyof JSX.IntrinsicElements', default: "'div'", description: 'Tag to render as.' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the root.' },
    {
      name: 'style',
      type: 'CSSProperties',
      description: 'Inline styles merged onto the root (composed with the timing custom properties).',
    },
    { name: 'children', type: 'ReactNode', description: 'The collapsing content.' },
  ],
  badge: [
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLSpanElement>, keyof BadgeOwnProps> & DataAttributes',
      description: 'Standard <span> attributes (aria-*, data-*, title, ...) forwarded to the chip.',
    },
    { name: 'tone', type: 'BadgeTone', default: "'neutral'", description: 'Status hue.' },
    { name: 'variant', type: "'glass' | 'outline'", default: "'glass'", description: 'Surface.' },
    {
      name: 'size',
      type: "'sm' | 'md'",
      default: "'md'",
      description: 'Chip density - `sm` tightens the vertical padding for inline use.',
    },
    { name: 'dot', type: 'boolean', description: 'Leading status dot.' },
    { name: 'live', type: 'boolean', description: 'Dot pulses (implies dot) - for in-progress status.' },
    { name: 'pill', type: 'boolean', description: 'Fully-rounded shape.' },
    { name: 'icon', type: 'ReactNode', description: 'Optional leading <Icon> (overrides dot if both set).' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the chip.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the chip.' },
    { name: 'children', type: 'ReactNode', description: 'Chip label.' },
  ],
  'status-badge': [
    {
      name: 'status',
      type: 'PostStatus',
      required: true,
      description:
        'Lifecycle state - maps to a canonical `tone` + label (`processing` also pulses live). Unknown falls back to `draft`.',
    },
    { name: 'morph', type: 'boolean', description: 'Morph in place as `status` changes instead of swapping.' },
    { name: 'variant', type: "'glass' | 'outline'", default: "'glass'", description: 'Surface.' },
    {
      name: 'size',
      type: "'sm' | 'md'",
      default: "'md'",
      description: 'Chip density - `sm` tightens the vertical padding for inline use.',
    },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the chip.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the chip.' },
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLSpanElement>, keyof BadgeOwnProps> & DataAttributes',
      description: 'Standard <span> attributes (aria-*, data-*, title, ...) forwarded to the chip.',
    },
    { name: 'dot', type: 'boolean', description: 'Leading status dot.' },
    { name: 'live', type: 'boolean', description: 'Dot pulses (implies dot) - for in-progress status.' },
    { name: 'pill', type: 'boolean', description: 'Fully-rounded shape.' },
    { name: 'icon', type: 'ReactNode', description: 'Optional leading <Icon> (overrides dot if both set).' },
  ],
  'count-badge': [
    {
      name: 'value',
      type: 'string | number',
      required: true,
      description: 'The chip content - stringified; in `roll` mode each digit becomes an odometer column.',
    },
    { name: 'roll', type: 'boolean', description: 'Odometer: digits roll vertically on change.' },
    { name: 'variant', type: "'glass' | 'outline'", default: "'glass'", description: 'Surface.' },
    {
      name: 'size',
      type: "'sm' | 'md'",
      default: "'md'",
      description: 'Chip density - `sm` tightens the vertical padding for inline use.',
    },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the chip.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the chip.' },
    { name: 'tone', type: 'BadgeTone', default: "'neutral'", description: 'Status hue.' },
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLSpanElement>, keyof BadgeOwnProps> & DataAttributes',
      description: 'Standard <span> attributes (aria-*, data-*, title, ...) forwarded to the chip.',
    },
    { name: 'dot', type: 'boolean', description: 'Leading status dot.' },
    { name: 'live', type: 'boolean', description: 'Dot pulses (implies dot) - for in-progress status.' },
    { name: 'pill', type: 'boolean', description: 'Fully-rounded shape.' },
    { name: 'icon', type: 'ReactNode', description: 'Optional leading <Icon> (overrides dot if both set).' },
  ],
  'text-field': [
    {
      name: 'htmlProps',
      type: "Omit<InputHTMLAttributes<HTMLInputElement>, keyof TextFieldOwnProps | 'size'> & DataAttributes",
      description: 'Standard <input> attributes (name, autoComplete, maxLength, aria-*, ...) forwarded to the input.',
    },
    {
      name: 'leadingIcon',
      type: 'ReactNode',
      description: 'Leading icon - your own icon node (sized to the control). Decorative.',
    },
    { name: 'clearable', type: 'boolean', description: "Show a clear button when there's a value." },
    { name: 'size', type: "'sm' | 'md' | 'lg'", description: 'Control height: sm 28 - md 36 (default) - lg 40.' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the field root.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the field root.' },
    {
      name: 'type',
      type: "'text' | 'search' | 'email' | 'url' | 'password'",
      description: 'Available text like types',
    },
    {
      name: 'warning',
      type: 'ReactNode',
      description: 'Warning message - amber state. Loses to `error`; wins over `success`/`helper`.',
    },
    {
      name: 'success',
      type: 'ReactNode',
      description: 'Success message - green state. Loses to `error`/`warning`; wins over `helper`.',
    },
    { name: 'id', type: 'string', description: 'Field id, ties the label to the control.' },
    {
      name: 'required',
      type: 'boolean',
      description: 'Mark the control required - reaches the native element and shows a danger `*` after the label.',
    },
    { name: 'optional', type: 'boolean', description: 'Show a muted "(optional)" after the label.' },
    { name: 'label', type: 'ReactNode', description: 'Label text (sentence case).' },
    {
      name: 'helper',
      type: 'ReactNode',
      description: "Neutral helper text - shown when there's no validation message.",
    },
    {
      name: 'error',
      type: 'ReactNode',
      description: 'Error message - sets the error state (border + icon + colour). Wins over warning/success/helper.',
    },
  ],
  'number-field': [
    {
      name: 'htmlProps',
      type: "Omit<InputHTMLAttributes<HTMLInputElement>, keyof NumberFieldOwnProps | 'size' | 'value' | 'onChange' | 'min' | 'max' | 'step'> & DataAttributes",
      description: 'Standard <input> attributes (name, aria-*, ...) forwarded to the input.',
    },
    { name: 'unit', type: 'string', description: 'Unit suffix shown inside the field (e.g. "days", "%").' },
    {
      name: 'min',
      type: 'number',
      default: '0',
      description: 'Minimum value - steps and committed typing clamp up to this; the decrease stepper disables here.',
    },
    {
      name: 'max',
      type: 'number',
      default: 'Infinity',
      description: 'Maximum value - steps and committed typing clamp down to this; the increase stepper disables here.',
    },
    {
      name: 'step',
      type: 'number',
      default: '1',
      description: 'Amount added/removed per ArrowUp/ArrowDown press and per caret stepper click. Decimals work.',
    },
    {
      name: 'value',
      type: 'number | string',
      description: 'Controlled numeric value. Omit for uncontrolled (use `defaultValue`).',
    },
    {
      name: 'defaultValue',
      type: 'number',
      default: '0',
      description: 'Uncontrolled initial value. Use instead of `value`.',
    },
    { name: 'onChange', type: '(value: number) => void', description: 'Called with the next clamped number.' },
    { name: 'disabled', type: 'boolean', description: 'Disabled - the input and both steppers go inert.' },
    { name: 'size', type: "'sm' | 'md' | 'lg'", description: 'Control height: sm - md (default) - lg.' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the field root.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the field root.' },
    { name: 'id', type: 'string', description: 'Field id, ties the label to the control.' },
    { name: 'label', type: 'ReactNode', description: 'Label text (sentence case).' },
    {
      name: 'helper',
      type: 'ReactNode',
      description: "Neutral helper text - shown when there's no validation message.",
    },
    {
      name: 'error',
      type: 'ReactNode',
      description: 'Error message - sets the error state (border + icon + colour). Wins over warning/success/helper.',
    },
  ],
  'otp-field': [
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLDivElement>, keyof OtpFieldOwnProps> & DataAttributes',
      description: 'Standard <div> attributes (aria-*, data-*, ...) forwarded to the root wrapper.',
    },
    { name: 'length', type: 'number', default: '6', description: 'Number of slots.' },
    { name: 'value', type: 'string', description: 'Controlled value (digit string).' },
    { name: 'onChange', type: '(value: string) => void', description: 'Called with the next value string.' },
    { name: 'group', type: 'number', description: 'Insert a separator every N slots (e.g. 3 - "-------").' },
    { name: 'error', type: 'boolean', description: 'Error state (red slots + ring).' },
    { name: 'disabled', type: 'boolean', description: 'Disable every slot.' },
    { name: 'size', type: "'sm'", description: 'Compact slot sizing. Only `sm`; omit for default.' },
    { name: 'className', type: 'string', description: 'Extra class(es) appended to the root wrapper.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the root wrapper.' },
  ],
  textarea: [
    {
      name: 'htmlProps',
      type: "Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, keyof TextareaOwnProps | 'rows'> & DataAttributes",
      description:
        'Standard <textarea> attributes (name, maxLength, aria-*, onKeyDown, ...) forwarded to the textarea.',
    },
    { name: 'value', type: 'string', default: "''", description: 'Controlled text value.' },
    {
      name: 'onChange',
      type: 'ChangeEventHandler<HTMLTextAreaElement>',
      description: 'Change handler - fired on each edit with the textarea change event.',
    },
    { name: 'onSubmit', type: '(value: string) => void', description: 'Fired on ⌘/Ctrl+Enter with the current text.' },
    {
      name: 'max',
      type: 'number',
      description:
        'Soft char limit: shows the meter + over-limit highlight. Does NOT truncate (use native maxLength for a hard stop).',
    },
    { name: 'minRows', type: 'number', default: '3', description: 'Rows shown before auto-grow kicks in.' },
    {
      name: 'maxRows',
      type: 'number',
      default: '10',
      description: 'Row cap - grows up to this, then the box scrolls.',
    },
    {
      name: 'warnAt',
      type: 'number',
      description: 'Remaining-chars threshold that flips the meter amber. Default 20.',
    },
    { name: 'hint', type: 'ReactNode', description: 'Footer hint, left of the meter - e.g. a ⌘↵ affordance.' },
    { name: 'size', type: "'md' | 'lg'", description: 'md (default) - lg (prominent composer).' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the field root.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the field root.' },
    {
      name: 'warning',
      type: 'ReactNode',
      description: 'Warning message - amber state. Loses to `error`; wins over `success`/`helper`.',
    },
    {
      name: 'success',
      type: 'ReactNode',
      description: 'Success message - green state. Loses to `error`/`warning`; wins over `helper`.',
    },
    { name: 'id', type: 'string', description: 'Field id, ties the label to the control.' },
    {
      name: 'required',
      type: 'boolean',
      description: 'Mark the control required - reaches the native element and shows a danger `*` after the label.',
    },
    { name: 'optional', type: 'boolean', description: 'Show a muted "(optional)" after the label.' },
    { name: 'label', type: 'ReactNode', description: 'Label text (sentence case).' },
    {
      name: 'helper',
      type: 'ReactNode',
      description: "Neutral helper text - shown when there's no validation message.",
    },
    {
      name: 'error',
      type: 'ReactNode',
      description: 'Error message - sets the error state (border + icon + colour). Wins over warning/success/helper.',
    },
  ],
  checkbox: [
    {
      name: 'htmlProps',
      type: "Omit<InputHTMLAttributes<HTMLInputElement>, keyof CheckboxOwnProps | 'type'> & DataAttributes",
      description: 'Standard <input> attributes (name, value, required, aria-*, ...) forwarded to the checkbox input.',
    },
    {
      name: 'checked',
      type: 'boolean',
      description: 'Controlled checked state. Omit for uncontrolled (use `defaultChecked`).',
    },
    { name: 'defaultChecked', type: 'boolean', description: 'Uncontrolled initial state.' },
    {
      name: 'indeterminate',
      type: 'boolean',
      default: 'false',
      description: 'Indeterminate - the "some, not all" select-all state; visually wins over `checked`.',
    },
    {
      name: 'error',
      type: 'boolean',
      default: 'false',
      description: 'Single error state for consent gates ("you must agree"); also sets `aria-invalid`.',
    },
    {
      name: 'disabled',
      type: 'boolean',
      description: 'Disabled - inert and de-emphasized (distinct fill when checked).',
    },
    {
      name: 'size',
      type: "'sm' | 'md'",
      default: "'md'",
      description: 'Box size: `md` 18px - `sm` 16px for dense table rows.',
    },
    { name: 'label', type: 'ReactNode', description: 'Label text beside the box.' },
    { name: 'description', type: 'ReactNode', description: 'Optional secondary line under the label (settings rows).' },
    {
      name: 'onChange',
      type: 'ChangeEventHandler<HTMLInputElement>',
      description: 'Fires on toggle - read `e.target.checked`.',
    },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the root label.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the root label.' },
  ],
  toggle: [
    {
      name: 'htmlProps',
      type: "Omit<InputHTMLAttributes<HTMLInputElement>, keyof ToggleOwnProps | 'type'> & DataAttributes",
      description: 'Standard <input> attributes (name, value, required, aria-*, ...) forwarded to the switch input.',
    },
    {
      name: 'checked',
      type: 'boolean',
      description: 'Controlled checked state. Omit for uncontrolled (use `defaultChecked`).',
    },
    { name: 'defaultChecked', type: 'boolean', description: 'Uncontrolled initial state.' },
    {
      name: 'disabled',
      type: 'boolean',
      description: 'Disabled - inert and de-emphasized (faded track, retains its position).',
    },
    {
      name: 'size',
      type: "'sm' | 'md'",
      default: "'md'",
      description: 'Track size: `md` 36x20 - `sm` 28x16 for dense settings/table rows.',
    },
    { name: 'label', type: 'ReactNode', description: 'Label text beside the track.' },
    { name: 'description', type: 'ReactNode', description: 'Optional secondary line under the label (settings rows).' },
    {
      name: 'onChange',
      type: 'ChangeEventHandler<HTMLInputElement>',
      description: 'Fires on flip - read `e.target.checked`.',
    },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the root label.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the root label.' },
  ],
  'radio-group': [
    {
      name: 'htmlProps',
      type: 'Omit<FieldsetHTMLAttributes<HTMLFieldSetElement>, keyof RadioGroupOwnProps> & DataAttributes',
      description: 'Standard <fieldset> attributes (aria-*, data-*, ...) forwarded to the root.',
    },
    {
      name: 'name',
      type: 'string',
      required: true,
      description: 'Shared radio name - ties the options into one keyboard group. Required.',
    },
    { name: 'value', type: 'string', description: 'The selected value (controlled).' },
    { name: 'onChange', type: '(value: string) => void', description: "Called with the chosen option's `value`." },
    { name: 'label', type: 'ReactNode', description: 'Group label / legend (sentence case).' },
    {
      name: 'helper',
      type: 'ReactNode',
      description: 'Persistent context shown under the legend, before the options.',
    },
    {
      name: 'error',
      type: 'ReactNode',
      description: 'Group-level error (e.g. required). Sets the error state + reveals the message.',
    },
    { name: 'variant', type: "'rows' | 'cards'", description: 'Skin: quiet rows (default) or selectable cards.' },
    {
      name: 'orientation',
      type: "'vertical' | 'horizontal'",
      description: 'Lay options out in a line instead of a stack.',
    },
    { name: 'size', type: "'sm' | 'md'", description: 'Control size: sm (dot 16) - md (default, dot 18).' },
    { name: 'disabled', type: 'boolean', description: 'Disable the whole group.' },
    { name: 'options', type: 'RadioOption[]', required: true, description: 'The options to choose between.' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the root element.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the root element.' },
    {
      name: 'required',
      type: 'boolean',
      description: 'Mark the control required - reaches the native element and shows a danger `*` after the label.',
    },
    { name: 'optional', type: 'boolean', description: 'Show a muted "(optional)" after the label.' },
  ],
  select: [
    {
      name: 'options',
      type: 'SelectOption[] | SelectGroup[]',
      default: '[]',
      required: true,
      description: 'The choices - a flat `SelectOption[]`, or `SelectGroup[]` to render labeled sections.',
    },
    {
      name: 'value',
      type: 'string | null',
      description:
        "Controlled value - matches an option's `value`, or `null` for none. Omit for uncontrolled (use `defaultValue`).",
    },
    { name: 'defaultValue', type: 'string | null', default: 'null', description: 'Initial value when uncontrolled.' },
    {
      name: 'onChange',
      type: '(value: string, option: SelectOption) => void',
      description: 'Fires on commit - gets the new `value` and its full `SelectOption`. Committing closes the menu.',
    },
    {
      name: 'placeholder',
      type: 'string',
      default: "'Select an option'",
      description: 'Trigger text when nothing is selected.',
    },
    { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Control height.' },
    {
      name: 'disabled',
      type: 'boolean',
      default: 'false',
      description: 'Disabled - trigger is inert and the menu cannot open.',
    },
    { name: 'invalid', type: 'boolean', default: 'false', description: 'Danger ring + border.' },
    {
      name: 'loading',
      type: 'boolean',
      default: 'false',
      description: 'Skeleton rows in the menu; trigger reads "Loading...".',
    },
    {
      name: 'searchable',
      type: 'boolean',
      default: 'false',
      description: 'Type-to-filter field pinned above the list.',
    },
    {
      name: 'searchPlaceholder',
      type: 'string',
      default: "'Filter options'",
      description: 'Placeholder for the `searchable` filter input.',
    },
    {
      name: 'leadingIcon',
      type: 'ReactNode',
      description: "Your own icon node pinned before the trigger label; else the selected option's icon.",
    },
    {
      name: 'id',
      type: 'string',
      description: 'Base id for the trigger/menu/list ids and a11y wiring; auto-generated if omitted.',
    },
    {
      name: 'ariaLabel',
      type: 'string',
      description: 'Accessible name for the trigger and listbox - supply when there is no visible label.',
    },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard <div> attributes (className, style, data-*, ...) forwarded to the select root.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      default: "duration 'base' + ease 'entrance'/'exit'",
      description: 'Menu open/close timing - motion tokens only, or `null` to disable.',
    },
    {
      name: 'triggerProps',
      type: 'SelectTriggerHtmlProps',
      description:
        'Standard <button> attributes (className, style, aria-*, data-*, ...) merged onto the trigger. `onClick` and `onKeyDown` run before the built-in open/close and arrow-key handling, which cannot be replaced - the trigger is the combobox.',
    },
    { name: 'showCheck', type: 'boolean', description: 'Show check icon on selected value' },
  ],
  'multi-select': [
    {
      name: 'options',
      type: 'SelectOption[] | SelectGroup[]',
      default: '[]',
      required: true,
      description: 'The choices - a flat `SelectOption[]`, or `SelectGroup[]` to render labeled sections.',
    },
    {
      name: 'value',
      type: 'string[]',
      description:
        'Controlled value - the array of selected option `value`s. Omit for uncontrolled (use `defaultValue`).',
    },
    { name: 'defaultValue', type: 'string[]', default: '[]', description: 'Initial selection when uncontrolled.' },
    {
      name: 'onChange',
      type: '(value: string[], toggled: SelectOption) => void',
      description: 'Fires with the NEXT array and the option that was toggled. Committing keeps the menu open.',
    },
    {
      name: 'placeholder',
      type: 'string',
      default: "'Select options'",
      description: 'Trigger text when nothing is selected.',
    },
    { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Control height.' },
    {
      name: 'disabled',
      type: 'boolean',
      default: 'false',
      description: 'Disabled - trigger is inert and the menu cannot open.',
    },
    { name: 'invalid', type: 'boolean', default: 'false', description: 'Danger ring + border.' },
    {
      name: 'loading',
      type: 'boolean',
      default: 'false',
      description: 'Skeleton rows in the menu; trigger reads "Loading...".',
    },
    {
      name: 'searchable',
      type: 'boolean',
      default: 'false',
      description: 'Type-to-filter field pinned above the list.',
    },
    {
      name: 'searchPlaceholder',
      type: 'string',
      default: "'Filter options'",
      description: 'Placeholder for the `searchable` filter input.',
    },
    {
      name: 'leadingIcon',
      type: 'ReactNode',
      description: "Your own icon node pinned before the trigger label; else the sole selected option's icon.",
    },
    {
      name: 'id',
      type: 'string',
      description: 'Base id for the trigger/menu/list ids and a11y wiring; auto-generated if omitted.',
    },
    {
      name: 'ariaLabel',
      type: 'string',
      description: 'Accessible name for the trigger and listbox - supply when there is no visible label.',
    },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard <div> attributes (className, style, data-*, ...) forwarded to the select root.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      default: "duration 'base' + ease 'entrance'/'exit'",
      description: 'Menu open/close timing - motion tokens only, or `null` to disable.',
    },
  ],
  avatar: [
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLSpanElement>, keyof AvatarOwnProps> & DataAttributes',
      description: 'Standard <span> attributes (onClick, title, data-*, ...) forwarded to the root.',
    },
    {
      name: 'src',
      type: 'string | null',
      description: 'Image URL. Falls back to initials / icon / silhouette if absent or fails.',
    },
    {
      name: 'name',
      type: 'string | null',
      description: 'Display name - drives initials generation, palette hash, and aria-label.',
    },
    {
      name: 'icon',
      type: 'ReactNode | null',
      description: 'Content override - any React node (e.g. <Icon name="globe" />).',
    },
    {
      name: 'shape',
      type: 'AvatarShape',
      description: "'circle' for people; 'square' for channels / brand pages. Default 'circle'.",
    },
    { name: 'size', type: 'AvatarSize', description: "Size step. Default 'md' (32 px)." },
    {
      name: 'status',
      type: 'AvatarStatus | null',
      description: 'Presence indicator dot at bottom-right. Default null (hidden).',
    },
    {
      name: 'paletteIndex',
      type: 'AvatarPaletteIndex | null',
      description:
        'Override identity slot 1-6 (blue - violet - plum - rose - clay - moss); auto from name hash when null, neutral when anonymous.',
    },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the root.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the root.' },
  ],
  tag: [
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLSpanElement>, keyof TagOwnProps> & DataAttributes',
      description: 'Standard <span> attributes forwarded to the tag root.',
    },
    { name: 'ref', type: 'Ref<HTMLSpanElement>', description: 'Ref to the tag root span.' },
    {
      name: 'children',
      type: 'ReactNode',
      required: true,
      description: 'Tag content; a string label also seeds the default remove-button `aria-label`.',
    },
    {
      name: 'icon',
      type: 'ReactNode | null',
      description: "Your own icon node, sized small and tinted to the tag's text.",
    },
    {
      name: 'onRemove',
      type: '(() => void) | null',
      description: 'Presence adds the remove button; called on click - remove the item yourself.',
    },
    {
      name: 'removeLabel',
      type: 'string',
      description: 'Accessible label for the remove button. Defaults to "Remove {label}" for string labels.',
    },
    { name: 'size', type: "'md' | 'sm'", description: "'md' = 28px (default) - 'sm' = 24px for dense rows." },
    {
      name: 'disabled',
      type: 'boolean',
      default: 'false',
      description: 'Set `data-disabled` on the tag and disable its remove button.',
    },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the root element.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the root element.' },
  ],
  table: [
    {
      name: 'columns',
      type: 'TableColumn<Row>[]',
      required: true,
      description: 'Column defs, rendered left to right.',
    },
    {
      name: 'rows',
      type: 'Row[]',
      required: true,
      description: 'The row data; sorted locally per the active sort before render.',
    },
    { name: 'rowKey', type: 'string', description: "Row identity property. Default 'id'. Must be unique and stable." },
    { name: 'ariaLabel', type: 'string', description: 'Accessible name for the <table>.' },
    {
      name: 'selectable',
      type: 'boolean',
      description: 'Checkbox column + bulk bar. Selection is a Set of row keys, owned here.',
    },
    {
      name: 'onSelectionChange',
      type: '(keys: Array<string | number>) => void',
      description: 'Fires with the selected row keys after every selection change.',
    },
    {
      name: 'bulkActions',
      type: '(keys: Array<string | number>, clear: () => void) => ReactNode',
      description: 'Rendered in the bulk bar between the count and the built-in Clear.',
    },
    {
      name: 'selectionLabel',
      type: '(row: Row) => string',
      description: "Per-row checkbox aria-label. Default 'Select row'.",
    },
    {
      name: 'defaultSort',
      type: 'TableSort | null',
      description: 'Initial sort; sorting stays local and uncontrolled after that.',
    },
    {
      name: 'onSortChange',
      type: '(sort: TableSort) => void',
      description: 'Notification only - fires after the local sort updates.',
    },
    {
      name: 'density',
      type: "'cozy' | 'compact'",
      description: "Row rhythm. Default 'cozy' (46px rows); 'compact' is 38px.",
    },
    {
      name: 'pinFirst',
      type: 'boolean',
      description: 'Pin checkbox + first column under horizontal overflow. Default true.',
    },
    { name: 'loading', type: 'boolean', description: 'Rows recede and go inert (list-fetch convention).' },
    {
      name: 'empty',
      type: 'ReactNode',
      description: "Shown when rows is empty and not loading. Default 'Nothing to show'.",
    },
    { name: 'footer', type: 'ReactNode', description: 'Footer strip - pagination, summaries.' },
    { name: 'onRowClick', type: '(row: Row) => void', description: 'Makes rows clickable (checkbox cell excluded).' },
    {
      name: 'className',
      type: 'string',
      description: 'Size the table here - the internal scroller absorbs the constraint.',
    },
    {
      name: 'htmlProps',
      type: "Omit<HTMLAttributes<HTMLDivElement>, 'className'> & DataAttributes",
      description: 'Standard <div> attributes (style, data-*, aria-*, ...) forwarded to the table wrapper.',
    },
  ],
  pagination: [
    {
      name: 'ariaLabel',
      type: 'string',
      default: "'Pagination'",
      description: 'Accessible name for the nav landmark - name the list ("Posts"), not "pagination".',
    },
    {
      name: 'range',
      type: '[number, number]',
      required: true,
      description: 'Items currently shown, 1-based inclusive: `[from, to]` (e.g. `[26, 50]`).',
    },
    {
      name: 'total',
      type: 'number | null',
      description: 'Total item count - render `of N` only when the API reports one; omit for endless lists.',
    },
    { name: 'hasPrev', type: 'boolean', default: 'false', description: 'A previous cursor exists.' },
    { name: 'hasNext', type: 'boolean', default: 'false', description: 'A next cursor exists.' },
    { name: 'onPrev', type: '() => void', description: 'Fired when the previous arrow is pressed.' },
    { name: 'onNext', type: '() => void', description: 'Fired when the next arrow is pressed.' },
    {
      name: 'loading',
      type: 'boolean',
      default: 'false',
      description: 'A page fetch is in flight: both arrows go inert, the clicked arrow carries the spinner.',
    },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the root element.' },
    {
      name: 'htmlProps',
      type: "Omit<HTMLAttributes<HTMLElement>, 'className'> & DataAttributes",
      description: 'Standard <nav> attributes (style, data-*, aria-*, ...) forwarded to the root.',
    },
  ],
  'date-field': [
    { name: 'value', type: 'string | null', description: "Controlled value, 'YYYY-MM-DD'." },
    {
      name: 'defaultValue',
      type: 'string | null',
      default: 'null',
      description: "Uncontrolled initial value, 'YYYY-MM-DD'. Use instead of `value`.",
    },
    {
      name: 'onChange',
      type: '(value: string) => void',
      description: "Fires on each day pick (commit is live), with the picked 'YYYY-MM-DD'.",
    },
    {
      name: 'placeholder',
      type: 'string',
      default: "'Pick a date'",
      description: 'Trigger text shown when no date is picked.',
    },
    {
      name: 'timezone',
      type: 'string',
      description:
        "IANA timezone name (e.g. 'Europe/Riga') - display context only, shown with its GMT offset in the footer.",
    },
    { name: 'min', type: 'string', description: "Earliest pickable date, 'YYYY-MM-DD', inclusive." },
    { name: 'max', type: 'string', description: "Latest pickable date, 'YYYY-MM-DD', inclusive." },
    { name: 'label', type: 'string', description: 'Field label rendered above the trigger.' },
    { name: 'required', type: 'boolean', default: 'false', description: 'Asterisk on the label.' },
    {
      name: 'invalid',
      type: 'boolean',
      default: 'false',
      description: 'Danger border + message color (.fld is-error).',
    },
    { name: 'message', type: 'string', description: 'Helper / error text under the field.' },
    { name: 'disabled', type: 'boolean', default: 'false', description: 'Disable the field.' },
    { name: 'className', type: 'string', description: 'Extra class on the field shell root.' },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard <div> attributes (style, data-*, aria-*, ...) forwarded to the field shell root.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      description:
        'Popover open/close timing - motion tokens only, or `null` to disable. (Not used by TimeField, which is inline.)',
    },
  ],
  'datetime-field': [
    { name: 'value', type: 'string | null', description: "Controlled value, 'YYYY-MM-DDTHH:mm'." },
    {
      name: 'defaultValue',
      type: 'string | null',
      default: 'null',
      description: "Uncontrolled initial value, 'YYYY-MM-DDTHH:mm'. Use instead of `value`.",
    },
    {
      name: 'onChange',
      type: '(value: string) => void',
      description: "Fires once both date and time are set, with 'YYYY-MM-DDTHH:mm' (an incomplete half never commits).",
    },
    {
      name: 'placeholder',
      type: 'string',
      default: "'Pick date & time'",
      description: 'Trigger text shown when no value is picked.',
    },
    {
      name: 'timezone',
      type: 'string',
      description: "IANA timezone (e.g. 'Europe/Riga') - display context, shown in the footer.",
    },
    { name: 'min', type: 'string', description: "Lower bound - 'YYYY-MM-DD' or 'YYYY-MM-DDTHH:mm', inclusive." },
    { name: 'max', type: 'string', description: "Upper bound - 'YYYY-MM-DD' or 'YYYY-MM-DDTHH:mm', inclusive." },
    { name: 'format', type: "'24h' | '12h'", description: "Time display only; storage stays 24h. Default '24h'." },
    {
      name: 'minuteStep',
      type: 'number',
      description: '↑/↓ step granularity in minutes (typing is exact). Default 5.',
    },
    { name: 'label', type: 'string', description: 'Field label rendered above the trigger.' },
    { name: 'required', type: 'boolean', default: 'false', description: 'Asterisk on the label.' },
    {
      name: 'invalid',
      type: 'boolean',
      default: 'false',
      description: 'Danger border + message color (.fld is-error).',
    },
    { name: 'message', type: 'string', description: 'Helper / error text under the field.' },
    { name: 'disabled', type: 'boolean', default: 'false', description: 'Disable the field.' },
    { name: 'className', type: 'string', description: 'Extra class on the field shell root.' },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard <div> attributes (style, data-*, aria-*, ...) forwarded to the field shell root.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      description:
        'Popover open/close timing - motion tokens only, or `null` to disable. (Not used by TimeField, which is inline.)',
    },
  ],
  'date-range': [
    { name: 'value', type: 'DateRange | null', description: 'Controlled value - both endpoints, or null when empty.' },
    {
      name: 'defaultValue',
      type: 'DateRange | null',
      default: 'null',
      description: 'Uncontrolled initial range. Use instead of `value`.',
    },
    {
      name: 'onChange',
      type: '(value: DateRange) => void',
      description: 'Fires only on a COMPLETE range (a lone anchor never commits).',
    },
    {
      name: 'placeholder',
      type: 'string',
      default: "'Pick a date range'",
      description: 'Trigger text shown when no range is picked.',
    },
    {
      name: 'timezone',
      type: 'string',
      description: "IANA timezone (e.g. 'Europe/Riga') - display context, shown in the footer.",
    },
    { name: 'min', type: 'string', description: "Earliest pickable date, 'YYYY-MM-DD', inclusive." },
    { name: 'max', type: 'string', description: "Latest pickable date, 'YYYY-MM-DD', inclusive." },
    { name: 'label', type: 'string', description: 'Field label rendered above the trigger.' },
    { name: 'required', type: 'boolean', default: 'false', description: 'Asterisk on the label.' },
    {
      name: 'invalid',
      type: 'boolean',
      default: 'false',
      description: 'Danger border + message color (.fld is-error).',
    },
    { name: 'message', type: 'string', description: 'Helper / error text under the field.' },
    { name: 'disabled', type: 'boolean', default: 'false', description: 'Disable the field.' },
    { name: 'className', type: 'string', description: 'Extra class on the field shell root.' },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard <div> attributes (style, data-*, aria-*, ...) forwarded to the field shell root.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      description:
        'Popover open/close timing - motion tokens only, or `null` to disable. (Not used by TimeField, which is inline.)',
    },
  ],
  'time-field': [
    { name: 'value', type: 'string | null', description: "Controlled value, canonical 'HH:mm' (24h)." },
    {
      name: 'defaultValue',
      type: 'string | null',
      default: 'null',
      description: "Uncontrolled initial value, 'HH:mm' (24h). Use instead of `value`.",
    },
    { name: 'onChange', type: '(value: string) => void', description: 'Fires live - the instant both segments exist.' },
    {
      name: 'label',
      type: 'string',
      description: "Field label rendered above the box; also the segments' `aria-label` fallback.",
    },
    { name: 'format', type: "'24h' | '12h'", description: "Display only; storage stays 24h. Default '24h'." },
    {
      name: 'minuteStep',
      type: 'number',
      description: '↑/↓ step granularity in minutes (typing is exact). Default 5.',
    },
    { name: 'min', type: 'string', description: "Lower bound 'HH:mm' - saturates, never errors." },
    { name: 'max', type: 'string', description: "Upper bound 'HH:mm' - saturates, never errors." },
    { name: 'required', type: 'boolean', default: 'false', description: 'Asterisk on the label.' },
    {
      name: 'invalid',
      type: 'boolean',
      default: 'false',
      description: 'Danger border + message color (.fld is-error).',
    },
    { name: 'message', type: 'string', description: 'Helper / error text under the field.' },
    { name: 'disabled', type: 'boolean', default: 'false', description: 'Disable the field.' },
    { name: 'className', type: 'string', description: 'Extra class on the field shell root.' },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard <div> attributes (style, data-*, aria-*, ...) forwarded to the field shell root.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      description:
        'Popover open/close timing - motion tokens only, or `null` to disable. (Not used by TimeField, which is inline.)',
    },
  ],
  tabs: [
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLDivElement>, keyof TabsOwnProps> & DataAttributes',
      description: 'Standard <div> attributes (data-*, aria-*, ...) forwarded to the root.',
    },
    { name: 'items', type: 'TabItem[]', default: '[]', required: true, description: 'The tab row, in order.' },
    {
      name: 'value',
      type: 'string | null | undefined',
      required: true,
      description: 'Controlled - the value of the active tab (null/undefined hides the ink).',
    },
    {
      name: 'onChange',
      type: '(value: string, dir: 1 | -1) => void',
      description:
        'Fires on click and on arrow-key travel (automatic activation). `dir` is the direction of travel (+1 right / -1 left) - hand it to TabPanel so content enters from the side the user moved toward.',
    },
    {
      name: 'name',
      type: 'string',
      description:
        'Shared id prefix wiring tab and panel aria. Give Tabs and its TabPanel the same `name`; omit it when the tabs have no managed panel.',
    },
    { name: 'ariaLabel', type: 'string', description: 'Accessible name for the tablist (e.g. "Section views").' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the root.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the root.' },
  ],
  alert: [
    {
      name: 'htmlProps',
      type: 'Omit<HTMLAttributes<HTMLDivElement>, keyof AlertOwnProps> & DataAttributes',
      description: 'Standard <div> attributes (aria-*, data-*, ...) forwarded to the alert.',
    },
    {
      name: 'tone',
      type: 'AlertTone',
      description: "Status of the message; info/success are polite, warning/danger assertive. Default 'info'.",
    },
    { name: 'title', type: 'ReactNode', required: true, description: 'The message - sentence case, ideally one line.' },
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Optional description; stays neutral - tone marks the message, not the prose.',
    },
    {
      name: 'action',
      type: 'AlertAction',
      description: 'One action max, rendered as the system secondary small button.',
    },
    {
      name: 'dismissible',
      type: 'boolean',
      description: 'Renders the always-visible close button. Uncontrolled unless `open` is given.',
    },
    {
      name: 'onDismiss',
      type: '() => void',
      description: 'Fires on dismiss. With `open` set, the parent owns hiding the alert.',
    },
    {
      name: 'open',
      type: 'boolean',
      description:
        'Controlled visibility; omit for uncontrolled. Exit scales down and fades; the slot it occupied is released when it unmounts, so content below moves up then rather than during.',
    },
    {
      name: 'banner',
      type: 'boolean',
      description: 'App-level strip: square corners, hairline below only. Paint modifier.',
    },
    { name: 'icon', type: 'ReactNode | null', description: 'Override the tone glyph; pass null to render no glyph.' },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the alert.' },
    { name: 'style', type: 'CSSProperties', description: 'Inline styles merged onto the alert.' },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      default: "entrance height 'slow'/'entrance' + opacity 'base'/'entrance'; exit scale + opacity 'fast'/'exit'",
      description: 'Enter/exit timing - motion tokens only, or `null` to disable (enter and exit snap).',
    },
  ],
  tooltip: [
    {
      name: 'content',
      type: 'ReactNode',
      required: true,
      description: 'The hint - a string or small node; never interactive content.',
    },
    {
      name: 'shortcut',
      type: 'string | null',
      description: 'Optional keyboard hint, rendered as mono metadata ("⌘↩", "S").',
    },
    {
      name: 'placement',
      type: 'Placement',
      description: 'Preferred side; flips automatically when out of viewport room.',
    },
    { name: 'disabled', type: 'boolean', description: 'Suppress the tooltip entirely (trigger renders untouched).' },
    {
      name: 'openDelay',
      type: 'number',
      description: 'ms before a cold hover shows; warm hovers + focus are instant. Default 350.',
    },
    {
      name: 'closeDelay',
      type: 'number',
      description: 'ms the bubble lingers after leaving (bridges moving to a neighbour). Default 140.',
    },
    {
      name: 'id',
      type: 'string',
      description:
        "Stable id for this trigger's store entry - lets overlapping triggers race safely under the one shared tooltip host. Not rendered to the DOM. Auto-generated when omitted.",
    },
    { name: 'children', type: 'ReactElement', required: true, description: 'Exactly one element.' },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLSpanElement> & DataAttributes',
      description: 'Standard <span> attributes forwarded to the anchor wrapper.',
    },
  ],
  dialog: [
    {
      name: 'open',
      type: 'boolean',
      description: 'Controlled open state. Omit for uncontrolled (use defaultOpen + trigger).',
    },
    { name: 'defaultOpen', type: 'boolean', default: 'false', description: 'Initial open state when uncontrolled.' },
    {
      name: 'onOpenChange',
      type: '(open: boolean) => void',
      description: 'Fires whenever the open state changes. Pair with `open` for controlled use.',
    },
    {
      name: 'trigger',
      type: 'ReactElement | null',
      description: 'Optional element cloned to open the dialog on click (uncontrolled ergonomics).',
    },
    {
      name: 'title',
      type: 'ReactNode',
      description: 'Header title - rendered as the `<h2>` and wired to `aria-labelledby`.',
    },
    {
      name: 'description',
      type: 'ReactNode',
      default: 'null',
      description: 'Subtext under the title - wired to `aria-describedby`.',
    },
    { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Panel width.' },
    {
      name: 'tone',
      type: "'default' | 'danger'",
      description: "'danger' tints the header icon badge + is the convention for destructive confirms.",
    },
    { name: 'icon', type: 'ReactNode', description: 'Your own icon node for the header badge (alert dialogs).' },
    { name: 'dismissible', type: 'boolean', description: 'Close button + backdrop/Esc dismissal. Default true.' },
    {
      name: 'container',
      type: 'HTMLElement | null',
      description:
        'Center inside this element instead of the viewport - it must be positioned (`position: relative` or similar). Scrim, scroll lock and inert scope to it; the rest of the page stays interactive.',
    },
    {
      name: 'footer',
      type: 'ReactNode | ((close: () => void) => ReactNode)',
      description: 'Action row - a node, or a render fn `(close) => node` so uncontrolled dialogs can dismiss.',
    },
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Dialog body - scrolls when tall; its scroll edges flag the header lift + footer divider.',
    },
    {
      name: 'id',
      type: 'string',
      description:
        "Base id for the panel; drives the trigger's `aria-controls` and the title/desc aria ids. Auto-generated when omitted.",
    },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLElement> & DataAttributes',
      description: 'Standard attributes (className, style, data-*, ...) forwarded to the dialog `<section>`.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      default: "open 'slow'/'entrance', close 'base'/'standard'",
      description: 'Open/close timing - motion tokens only, or `null` to disable.',
    },
  ],
  popover: [
    { name: 'open', type: 'boolean', description: 'Controlled open state. Omit to stay uncontrolled.' },
    { name: 'defaultOpen', type: 'boolean', description: 'Initial state when uncontrolled. Default false.' },
    {
      name: 'onOpenChange',
      type: '(open: boolean) => void',
      description: 'Fires whenever the open state changes. Pair with `open` for controlled use.',
    },
    {
      name: 'trigger',
      type: 'ReactElement | null',
      description: 'Cloned to toggle the panel, and used as the anchor unless `anchor` is set.',
    },
    {
      name: 'anchor',
      type: 'VirtualAnchor | null',
      description:
        'Anchor to an arbitrary rect instead of the trigger - any `{ getBoundingClientRect() }`, which an element also satisfies. Drive `open` yourself; pass a new object to re-place a moving anchor.',
    },
    {
      name: 'side',
      type: "'top' | 'bottom' | 'left' | 'right'",
      description: "Preferred side; flips to the opposite side when cramped. Default 'bottom'.",
    },
    {
      name: 'align',
      type: "'start' | 'center' | 'end'",
      description: "Cross-axis alignment against the trigger. Default 'start'.",
    },
    { name: 'arrow', type: 'boolean', description: 'Caret tracking the trigger center. Default false.' },
    { name: 'dismissible', type: 'boolean', description: 'Esc + outside-press dismissal. Default true.' },
    {
      name: 'id',
      type: 'string',
      description: "Base id for the panel; drives the trigger's `aria-controls`. Auto-generated when omitted.",
    },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard attributes (className, style, data-*, ...) forwarded to the popover panel.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      default: "open 'base'/'entrance', close 'fast'/'exit'",
      description: 'Open/close timing - motion tokens only, or `null` to disable.',
    },
    {
      name: 'children',
      type: 'ReactNode',
      required: true,
      description: 'The ENTIRE surface - paint AND semantics. Drive dismissal with `open`/`onOpenChange`.',
    },
  ],
  dropdown: [
    {
      name: 'items',
      type: 'DropdownItems',
      default: '[]',
      required: true,
      description:
        'The rows - a flat `DropdownItem[]`, or `DropdownGroup[]` to render divided sections. A row with its own `items` opens a submenu instead of committing.',
    },
    {
      name: 'trigger',
      type: 'ReactElement',
      required: true,
      description: 'Cloned to toggle the menu, and used as the anchor. Gets the `aria-haspopup="menu"` wiring.',
    },
    { name: 'open', type: 'boolean', description: 'Controlled open state. Omit to stay uncontrolled.' },
    { name: 'defaultOpen', type: 'boolean', default: 'false', description: 'Initial state when uncontrolled.' },
    {
      name: 'onOpenChange',
      type: '(open: boolean) => void',
      description: 'Fires whenever the open state changes. Pair with `open` for controlled use.',
    },
    {
      name: 'onSelect',
      type: '(id: string, item: DropdownItem) => void',
      description: 'Fires when a row commits - gets its `id` and the full item. Committing closes every level.',
    },
    {
      name: 'side',
      type: "'top' | 'bottom' | 'left' | 'right'",
      default: "'bottom'",
      description: 'Preferred side of the trigger; flips to the opposite side when cramped.',
    },
    {
      name: 'align',
      type: "'start' | 'center' | 'end'",
      default: "'start'",
      description: 'Cross-axis alignment against the trigger. Submenus always align to their row.',
    },
    {
      name: 'id',
      type: 'string',
      description:
        "Base id for the menu and its rows; drives the trigger's `aria-controls`. Auto-generated when omitted.",
    },
    {
      name: 'ariaLabel',
      type: 'string',
      description: "Accessible name for the menu - supply when the trigger's own label does not describe it.",
    },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard attributes (className, style, data-*, ...) forwarded to the top-level menu panel.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      default: "open 'base'/'entrance', close 'fast'/'exit'",
      description: 'Open/close timing - motion tokens only, or `null` to disable.',
    },
  ],
  sheet: [
    { name: 'open', type: 'boolean', description: 'Controlled open state. Omit to stay uncontrolled.' },
    { name: 'defaultOpen', type: 'boolean', description: 'Initial state when uncontrolled. Default false.' },
    {
      name: 'onOpenChange',
      type: '(open: boolean) => void',
      description: 'Fires whenever the open state changes. Pair with `open` for controlled use.',
    },
    { name: 'trigger', type: 'ReactElement | null', description: 'Cloned to open the sheet on click.' },
    { name: 'side', type: "'right' | 'bottom'", description: "Edge the sheet slides in from. Default 'right'." },
    { name: 'dismissible', type: 'boolean', description: 'Scrim/Esc dismissal + drag-to-edge. Default true.' },
    {
      name: 'container',
      type: 'HTMLElement | null',
      description:
        'Dock inside this element instead of the viewport - it must be positioned (`position: relative` or similar). Scrim, scroll lock and inert scope to it; the rest of the page stays interactive.',
    },
    {
      name: 'id',
      type: 'string',
      description: "Base id for the panel; drives the trigger's `aria-controls`. Auto-generated when omitted.",
    },
    {
      name: 'htmlProps',
      type: 'HTMLAttributes<HTMLDivElement> & DataAttributes',
      description: 'Standard attributes (className, style, data-*, ...) forwarded to the sheet panel.',
    },
    {
      name: 'animation',
      type: 'DisableableAnimation',
      default: "open 'slow'/'entrance', close 'base'/'exit'",
      description: 'Open/close timing - motion tokens only, or `null` to disable.',
    },
    {
      name: 'children',
      type: 'ReactNode',
      required: true,
      description: 'The ENTIRE surface - paint AND semantics. Drive dismissal with `open`/`onOpenChange`.',
    },
  ],
  'emoji-picker': [
    {
      name: 'open',
      type: 'boolean',
      required: true,
      description: 'Controlled open state - the panel has no uncontrolled mode.',
    },
    {
      name: 'onOpenChange',
      type: '(open: boolean) => void',
      required: true,
      description: 'Fires whenever the panel asks to open or close: trigger press, Esc, outside press, sheet drag.',
    },
    {
      name: 'onSelect',
      type: '(shortcode: string, hexId: string) => void',
      required: true,
      description: "Fires on pick, with the primary shortcode (`smile`, no colons) and the emoji's hex id.",
    },
    {
      name: 'getEmojiUrl',
      type: 'GetEmojiUrl',
      required: true,
      description:
        'Builds the image URL for one emoji at one call site. Pass the bundled `getEmojiUrl` to use Twemoji and Noto.',
    },
    {
      name: 'trigger',
      type: 'ReactElement | null',
      description: 'Element that both opens the panel and anchors it, when there is no anchor.',
    },
    {
      name: 'offset',
      type: 'number',
      description:
        'Gap in pixels between a custom `popoverProps.anchor` and the panel. Ignored when the panel anchors to its trigger.',
    },
    {
      name: 'search',
      type: 'boolean',
      description:
        "Render the panel's own search field. Always on in sheet mode, where the sheet traps focus and an outside query can no longer reach the panel.",
    },
    {
      name: 'query',
      type: 'string',
      description: 'Drive the results from outside — a `:` chip in a document, your own input.',
    },
    { name: 'breakpoint', type: 'string', description: 'Viewport at which the panel becomes a bottom sheet.' },
    {
      name: 'popoverProps',
      type: 'Omit<PopoverProps, Forwarded>',
      description: 'Desktop placement — `anchor`, `side`, `align`, `arrow`, and every other Popover knob.',
    },
    {
      name: 'sheetProps',
      type: "Omit<SheetProps, Forwarded | 'side'>",
      description: 'Narrow-viewport docking — `container`, `dismissible`, and every other Sheet knob.',
    },
    { name: 'className', type: 'string', description: 'Extra class(es) merged onto the panel frame.' },
    {
      name: 'ref',
      type: 'Ref<EmojiPickerHandle>',
      description:
        'Imperative handle - drive the grid from your own field: `handleKey`, `selectFocused`, `renderAll`, `renderFiltered`.',
    },
  ],
};

export const GENERATED_TYPES: Record<string, NestedType[]> = {
  'radio-group': [
    {
      name: 'RadioOption',
      rows: [
        {
          name: 'value',
          type: 'string',
          required: true,
          description: 'The stored value - what `onChange` returns and `value` matches.',
        },
        { name: 'label', type: 'ReactNode', required: true, description: 'Visible label (sentence case).' },
        {
          name: 'description',
          type: 'ReactNode',
          description: 'Optional secondary line (muted) explaining the choice.',
        },
        { name: 'icon', type: 'ReactNode', description: 'Leading icon - your own node. CARDS only; ignored for rows.' },
        { name: 'disabled', type: 'boolean', description: 'Disable just this option.' },
      ],
    },
  ],
  select: [
    {
      name: 'SelectGroup',
      rows: [
        {
          name: 'label',
          type: 'string',
          description: 'Section heading rendered above the options; omit for an unlabeled group.',
        },
        { name: 'options', type: 'SelectOption[]', required: true, description: 'The options in this section.' },
      ],
    },
    {
      name: 'SelectOption',
      rows: [
        {
          name: 'value',
          type: 'string',
          required: true,
          description: 'The stored value - what `onChange` returns and `value` matches; must be unique.',
        },
        {
          name: 'label',
          type: 'ReactNode',
          required: true,
          description: 'Primary row text, and the trigger label once selected; also matched by `searchable`.',
        },
        {
          name: 'description',
          type: 'string',
          description: 'Optional secondary line under the label; also matched by `searchable`.',
        },
        { name: 'icon', type: 'ReactNode', description: 'Your own icon node shown before the label.' },
        {
          name: 'disabled',
          type: 'boolean',
          default: 'false',
          description: 'Not selectable - skipped by keyboard nav and typeahead, and marked `aria-disabled`.',
        },
        {
          name: 'searchText',
          type: 'string',
          description: 'Text used for `searchable` filtering and typeahead. Required when `label` is not a string.',
        },
      ],
    },
  ],
  'multi-select': [
    {
      name: 'SelectGroup',
      rows: [
        {
          name: 'label',
          type: 'string',
          description: 'Section heading rendered above the options; omit for an unlabeled group.',
        },
        { name: 'options', type: 'SelectOption[]', required: true, description: 'The options in this section.' },
      ],
    },
    {
      name: 'SelectOption',
      rows: [
        {
          name: 'value',
          type: 'string',
          required: true,
          description: 'The stored value - what `onChange` returns and `value` matches; must be unique.',
        },
        {
          name: 'label',
          type: 'ReactNode',
          required: true,
          description: 'Primary row text, and the trigger label once selected; also matched by `searchable`.',
        },
        {
          name: 'description',
          type: 'string',
          description: 'Optional secondary line under the label; also matched by `searchable`.',
        },
        { name: 'icon', type: 'ReactNode', description: 'Your own icon node shown before the label.' },
        {
          name: 'disabled',
          type: 'boolean',
          default: 'false',
          description: 'Not selectable - skipped by keyboard nav and typeahead, and marked `aria-disabled`.',
        },
        {
          name: 'searchText',
          type: 'string',
          description: 'Text used for `searchable` filtering and typeahead. Required when `label` is not a string.',
        },
      ],
    },
  ],
  table: [
    {
      name: 'TableColumn',
      rows: [
        {
          name: 'key',
          type: 'string',
          required: true,
          description: 'Unique column id; also the default data accessor (row[key]).',
        },
        {
          name: 'label',
          type: 'ReactNode',
          description: 'Header cell content; omit for a header-less column (e.g. an actions column).',
        },
        { name: 'align', type: 'TableAlign', description: "Cell + header alignment. Default 'start'." },
        {
          name: 'mono',
          type: 'boolean',
          description: 'Mono + tabular numerals (timestamps, counts, IDs - section E).',
        },
        { name: 'strong', type: 'boolean', description: 'Identity emphasis: strong text, medium weight.' },
        {
          name: 'grow',
          type: 'boolean',
          description: 'The one greedy column - absorbs slack width. Others size to content.',
        },
        {
          name: 'sortable',
          type: 'boolean',
          description: 'Header becomes a sort control. Sort is local; asc - desc, no third state.',
        },
        {
          name: 'sortBy',
          type: 'string | ((row: Row) => unknown)',
          description: 'Sort accessor: a row property name, or a function. Defaults to row[key].',
        },
        {
          name: 'hideBelow',
          type: 'TableHideBelow',
          description: 'Collapse this column below a container breakpoint (30rem / 42rem).',
        },
        { name: 'render', type: '(row: Row) => ReactNode', description: 'Custom cell renderer. Defaults to row[key].' },
      ],
    },
    {
      name: 'TableSort',
      rows: [
        { name: 'key', type: 'string', required: true, description: '`key` of the column being sorted by.' },
        { name: 'dir', type: "'asc' | 'desc'", required: true, description: 'Sort direction - `asc` or `desc`.' },
      ],
    },
  ],
  'date-range': [
    {
      name: 'DateRange',
      rows: [
        { name: 'start', type: 'string', required: true, description: "Range start, inclusive - `'YYYY-MM-DD'`." },
        {
          name: 'end',
          type: 'string',
          required: true,
          description: "Range end, inclusive - `'YYYY-MM-DD'`. Never before `start`.",
        },
      ],
    },
  ],
  tabs: [
    {
      name: 'TabItem',
      rows: [
        {
          name: 'value',
          type: 'string',
          required: true,
          description: 'Stable identity - also used in the tab/panel id pair.',
        },
        { name: 'label', type: 'ReactNode', required: true, description: 'Visible tab text.' },
        { name: 'icon', type: 'ReactNode', description: 'Leading icon - your own node.' },
        {
          name: 'count',
          type: 'number | string',
          description: 'Rendered mono + tabular. Pass a number or a preformatted string.',
        },
        {
          name: 'disabled',
          type: 'boolean',
          description: 'Dims the tab, blocks selection, and skips it during arrow-key travel.',
        },
      ],
    },
  ],
  alert: [
    {
      name: 'AlertAction',
      rows: [
        { name: 'label', type: 'string', required: true, description: 'Sentence-case label, e.g. "Update billing".' },
        { name: 'onClick', type: '() => void', description: '' },
      ],
    },
  ],
  popover: [
    {
      name: 'VirtualAnchor',
      rows: [{ name: 'getBoundingClientRect', type: 'DOMRect', required: true, description: '' }],
    },
  ],
  dropdown: [
    {
      name: 'DropdownGroup',
      rows: [
        {
          name: 'label',
          type: 'string',
          description: 'Section heading rendered above the rows; omit for an unlabeled but still divided group.',
        },
        { name: 'items', type: 'DropdownItem[]', required: true, description: 'The rows in this section.' },
      ],
    },
    {
      name: 'DropdownItem',
      rows: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: "Unique id - what `onSelect` receives, and what identifies this row's open submenu.",
        },
        { name: 'label', type: 'ReactNode', required: true, description: 'Primary row text.' },
        { name: 'description', type: 'string', description: 'Optional secondary line under the label.' },
        { name: 'icon', type: 'ReactNode', description: 'Your own icon node shown before the label.' },
        {
          name: 'shortcut',
          type: 'string',
          description: 'Keyboard hint shown at the trailing edge, mono. Display only - you still bind the key.',
        },
        {
          name: 'danger',
          type: 'boolean',
          default: 'false',
          description: 'Destructive action - the row reads in the danger hue.',
        },
        {
          name: 'disabled',
          type: 'boolean',
          default: 'false',
          description: 'Not selectable - skipped by arrow keys and typeahead, and marked `aria-disabled`.',
        },
        {
          name: 'items',
          type: 'DropdownItem[] | DropdownGroup[]',
          description: 'Nested menu. The row opens it instead of committing, and can nest again without limit.',
        },
        {
          name: 'searchText',
          type: 'string',
          description: 'Text used for typeahead. Required when `label` is not a string.',
        },
        {
          name: 'onSelect',
          type: '() => void',
          description: "Fires when this row commits, before the menu's own `onSelect`.",
        },
      ],
    },
  ],
  'emoji-picker': [
    {
      name: 'EmojiPickerHandle',
      rows: [
        {
          name: 'renderAll',
          type: '() => void',
          required: true,
          description: 'Redraw the full category grid, dropping whatever query was showing.',
        },
        {
          name: 'renderFiltered',
          type: '(next: string) => void',
          required: true,
          description: 'Redraw the grid as the ranked results for `next`, with the first hit already marked.',
        },
        {
          name: 'handleKey',
          type: '(event: KeyboardEvent) => boolean',
          required: true,
          description:
            'Feed a key event from your own field into the grid - arrows move, Enter picks. Returns true when the grid consumed the key, so you can leave the rest to your input.',
        },
        {
          name: 'selectFocused',
          type: '() => void',
          required: true,
          description: 'Commit the tile the marker is on, exactly as a click on it would.',
        },
      ],
    },
  ],
};
