import madge from 'madge';
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, sep } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const SRC = join(ROOT, 'src');
const DOCS = join(ROOT, 'docs');

const CODE_EXTENSIONS = ['.ts', '.tsx'];
const ALL_EXTENSIONS = [...CODE_EXTENSIONS, '.css'];

const walk = (dir, exts) =>
  existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true, recursive: true })
        .filter((d) => d.isFile() && exts.some((e) => d.name.endsWith(e)))
        .map((d) => join(d.parentPath, d.name))
    : [];

const relative = (file) =>
  file
    .slice(SRC.length + 1)
    .split(sep)
    .join('/');
const lineCount = (file) => readFileSync(file, 'utf8').split('\n').length;
const thousands = (n) => n.toLocaleString('en-US');

const ROLE_BY_PREFIX = [
  ['engine/', 'the WAAPI engine'],
  ['motion/', 'the React motion layer'],
  ['tokens/', 'the token vocabulary'],
  ['components/internal/', 'shared internal machinery'],
  ['components/primitives/', 'a primitive'],
  ['components/composites/', 'a composite'],
  ['components/compound/', 'a compound pattern'],
  ['mcp/', 'the bundled MCP server'],
  ['components/dev/', 'developer tooling'],
];
const roleOf = (module) => ROLE_BY_PREFIX.find(([prefix]) => module.startsWith(prefix))?.[1] ?? 'library code';

function componentFolder(file) {
  const parts = relative(file).split('/');
  if (parts[0] !== 'components' || parts.length < 3) return null;
  return `${parts[1]}/${parts[2]}`;
}

async function importGraph() {
  const result = await madge(SRC, { fileExtensions: ['ts', 'tsx'] });
  const graph = result.obj();
  const circular = result.circular();

  const inDegree = new Map();
  for (const module of Object.keys(graph)) inDegree.set(module, 0);
  for (const dependencies of Object.values(graph))
    for (const dependency of dependencies) inDegree.set(dependency, (inDegree.get(dependency) ?? 0) + 1);

  const modules = [...inDegree.keys()].filter((m) => CODE_EXTENSIONS.some((e) => m.endsWith(e)));
  const hubs = modules
    .map((module) => [module, inDegree.get(module)])
    .filter(([, count]) => count >= 4)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));

  const cssImporters = new Map();
  for (const file of walk(SRC, CODE_EXTENSIONS)) {
    const dir = relative(file).split('/').slice(0, -1).join('/');
    for (const m of readFileSync(file, 'utf8').matchAll(/^import\s+'([^']+\.css)'/gm)) {
      const target = m[1].startsWith('.') ? `${dir}/${m[1].replace(/^\.\//, '')}` : m[1];
      cssImporters.set(target, (cssImporters.get(target) ?? 0) + 1);
    }
  }
  const sharedCss = [...cssImporters.entries()]
    .filter(([, count]) => count > 1)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));

  const lines = [
    '# Import graph',
    '',
    'Internal module dependencies in `src/`, from [`madge`](https://github.com/pahen/madge).',
    '',
    '<!-- generated by scripts/gen-docs.mjs - run `pnpm docs:gen`, do not edit by hand -->',
    '',
    `- **Modules analysed:** ${modules.length} (\`.ts\` / \`.tsx\`)`,
    `- **Circular dependencies:** ${circular.length ? `${circular.length} - see below` : 'none'}`,
    '',
    '## Hubs',
    '',
    'Modules imported by four or more others. A change here ripples widest.',
    '',
    '| In-degree | Module | Part of |',
    '| --------: | ------ | ------- |',
    ...hubs.map(([module, count]) => `| ${count} | \`${module}\` | ${roleOf(module)} |`),
    '',
  ];

  if (sharedCss.length) {
    lines.push(
      '## Shared stylesheets',
      '',
      'Stylesheets imported by more than one module. Every other `.css` file is imported',
      'only by its own component, which is what `pnpm check:css` enforces.',
      '',
      '| Importers | Stylesheet |',
      '| --------: | ---------- |',
      ...sharedCss.map(([file, count]) => `| ${count} | \`${file}\` |`),
      '',
    );
  }

  if (circular.length) {
    lines.push(
      '## Circular dependencies',
      '',
      ...circular.map((cycle) => `- ${cycle.map((m) => `\`${m}\``).join(' -> ')}`),
      '',
    );
  }

  return {
    file: 'import-graph.md',
    content: lines.join('\n'),
    summary: `${modules.length} modules, ${circular.length} cycles`,
  };
}

function componentSizes() {
  const files = walk(SRC, ALL_EXTENSIONS);

  const folders = new Map();
  for (const file of files) {
    const folder = componentFolder(file);
    if (!folder) continue;
    const entry = folders.get(folder) ?? { code: 0, css: 0 };
    if (file.endsWith('.css')) entry.css += lineCount(file);
    else entry.code += lineCount(file);
    folders.set(folder, entry);
  }

  const ranked = [...folders.entries()]
    .map(([folder, { code, css }]) => ({ folder, code, css, total: code + css }))
    .sort((a, b) => b.total - a.total);

  const biggestFiles = files
    .map((file) => ({ file: relative(file), lines: lineCount(file) }))
    .sort((a, b) => b.lines - a.lines)
    .slice(0, 15);

  const totalCode = files.filter((f) => !f.endsWith('.css')).reduce((sum, f) => sum + lineCount(f), 0);
  const totalCss = files.filter((f) => f.endsWith('.css')).reduce((sum, f) => sum + lineCount(f), 0);

  const lines = [
    '# Component sizes',
    '',
    'Lines of code across `src/` (`.tsx`, `.ts`, `.css`).',
    '',
    '<!-- generated by scripts/gen-docs.mjs - run `pnpm docs:gen`, do not edit by hand -->',
    '',
    `- **Total:** ${thousands(totalCode + totalCss)} lines - ${thousands(totalCode)} code, ${thousands(totalCss)} CSS`,
    `- **Component folders:** ${ranked.length}`,
    '',
    '## Component folders',
    '',
    'Aggregated across every file in the folder, since one component often spans',
    'several files.',
    '',
    '| Rank | Folder | Total | Code | CSS |',
    '| ---: | ------ | ----: | ---: | --: |',
    ...ranked.map(
      (r, i) => `| ${i + 1} | \`${r.folder}\` | ${thousands(r.total)} | ${thousands(r.code)} | ${thousands(r.css)} |`,
    ),
    '',
    '## Largest individual files',
    '',
    '| Rank | File | Lines |',
    '| ---: | ---- | ----: |',
    ...biggestFiles.map((f, i) => `| ${i + 1} | \`${f.file}\` | ${thousands(f.lines)} |`),
    '',
  ];

  return {
    file: 'component-sizes.md',
    content: lines.join('\n'),
    summary: `${ranked.length} folders, ${thousands(totalCode + totalCss)} lines`,
  };
}

const generated = [await importGraph(), componentSizes()];
const checkOnly = process.argv.includes('--check');

if (checkOnly) {
  const stale = generated.filter(({ file, content }) => {
    const path = join(DOCS, file);
    return !existsSync(path) || readFileSync(path, 'utf8') !== content;
  });
  if (stale.length) {
    for (const { file } of stale) console.error(`\u2717 docs/${file} is out of date - run "pnpm docs:gen".`);
    process.exit(1);
  }
  console.log(`gen-docs --check: ${generated.map((g) => `docs/${g.file}`).join(', ')} up to date.`);
} else {
  for (const { file, content } of generated) writeFileSync(join(DOCS, file), content);
  console.log(`gen-docs: ${generated.map((g) => `${g.file} (${g.summary})`).join(', ')}.`);
}
